branch-defaults:
  develop:
    environment: teambarometer
global:
  application_name: teambarometer
  default_ec2_keyname: teambarometer
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Puma)
  default_region: us-east-2