branch-defaults:
  develop:
    environment: teambarometer-dev
global:
  application_name: teambarometer
  default_ec2_keyname: teambarometer
  default_platform: 64bit Amazon Linux 2017.09 v2.6.0 running Java 8
  default_region: us-east-2
  deploy: ~/repo/build/libs/application.jar